### ISSUE TITLE
Error 'Cannot add property scale, object is not extensible' in lovelace

### ISSUE THREAD

**Issue by Spirituss** [jcooper-korg/AlarmPanel#4]
After the last card-mod and other updates lovelace shows this error on the place of the card:
**Cannot add property scale, object is not extensible**

<img width="517" alt="Снимок экрана 2021-04-07 в 21 00 59" src="https://user-images.githubusercontent.com/47206760/113897937-0eacd200-97d4-11eb-9eff-8502e07070ca.png">

I receive the same error with the original forked card. Any ideas?

**Comment by jcooper-korg** [comment]
I'm not seeing that here, and I'm up-to-date.  I have my card scale set to 13px.

what HA version are you on?  also, please send me your card config.

Here's my version info
<img width="516" alt="Screen Shot 2021-04-07 at 6 46 58 AM" src="https://user-images.githubusercontent.com/1987267/113908470-6bd06580-978b-11eb-86a0-4a831aab7d3b.png">

**Comment by Spirituss** [comment]
This is my lovelace config:
```
views: 
- id: security
  cards:
      - type: custom:alarm_control_panel-card 
        entity: alarm_control_panel.home_alarm
        display_letters: false
        states:
          - arm_home
          - arm_away
```

<img width="556" alt="Снимок экрана 2021-04-07 в 22 53 48" src="https://user-images.githubusercontent.com/47206760/113912284-9cdc8480-97e3-11eb-8bd2-9b77ff5a5aff.png">

**Comment by jcooper-korg** [comment]
thanks for the response.  I tried your config and also see an error!  I was able to work around it by adding the scale property to the config.  E.g.
```
views: 
- id: security
  cards:
      - type: custom:alarm_control_panel-card 
        entity: alarm_control_panel.home_alarm
        display_letters: false
        scale: 13px
        states:
          - arm_home
          - arm_away
```

but that shouldn't be required! I'll look into a fix
